BINS=main.elf

OBJS= lib/uart.o lib/sensor.o lib/port.o lib/fan.o lib/led.o lib/profilazione.o lib/linked_list_with_id_and_pin.o lib/eeprom_manager.o

HEADERS= lib/uart.h lib/sensor.h lib/port.h ../avr_client_common/packets.h lib/fan.h lib/led.h lib/profilazione.h lib/linked_list_with_id_and_pin. lib/eeprom_manager.h lib/buffer_utils.h

CROSS_PLATFROM = ../avr_client_common/serial_protocol.* ../avr_client_common/linked_list_with_id.* ../avr_client_common/color.*

include avr_common/avr.mk
